name: Deploy
on:
  release:
    tags:
      - v*
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: whoami
